// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Env precedence: load `.env.local` first (local dev), then `.env`. dotenv does
// NOT override variables already set, so `.env.local` wins locally. In production
// neither file exists (docker injects env vars), so both calls are no-ops and
// DATABASE_URL still comes from the container environment.
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
