import {
  Body,
  Controller,
  Get,
  HttpCode,
  Post,
  UseGuards,
} from '@nestjs/common';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { CurrentUser } from '../auth/current-user.decorator';
import type { AuthUser } from '../auth/current-user.decorator';
import { WorkoutPlanService } from './workout-plan.service';
import { CreateWeeklyPlanDto } from './dto/create-weekly-plan.dto';
import {
  RescheduleSessionDto,
  SessionActionDto,
} from './dto/session-action.dto';

/**
 * Authenticated, DB-backed weekly workout plan. Distinct day-wise sessions are
 * generated by the deterministic engine and persisted, then mutated by the
 * complete / skip / reschedule / shorter / rebalance lifecycle actions.
 *
 * NOTE: these paths are intentionally session-scoped (`/workouts/session/...`)
 * so they never collide with the existing public, stateless demo endpoints
 * (`POST /workouts/generate|complete|skip|adjust-week`).
 */
@Controller('workouts')
@UseGuards(JwtAuthGuard)
export class WorkoutPlanController {
  constructor(private readonly plans: WorkoutPlanService) {}

  @Post('weekly-plan')
  @HttpCode(200)
  createWeeklyPlan(
    @CurrentUser() user: AuthUser,
    @Body() dto: CreateWeeklyPlanDto,
  ) {
    return this.plans.createWeeklyPlan(user.userId, dto);
  }

  @Get('weekly-plan/current')
  getCurrent(@CurrentUser() user: AuthUser) {
    return this.plans.getCurrent(user.userId);
  }

  @Post('session/complete')
  @HttpCode(200)
  complete(@CurrentUser() user: AuthUser, @Body() dto: SessionActionDto) {
    return this.plans.completeSession(user.userId, dto.sessionId);
  }

  @Post('session/skip')
  @HttpCode(200)
  skip(@CurrentUser() user: AuthUser, @Body() dto: SessionActionDto) {
    return this.plans.skipSession(user.userId, dto.sessionId);
  }

  @Post('session/reschedule')
  @HttpCode(200)
  reschedule(
    @CurrentUser() user: AuthUser,
    @Body() dto: RescheduleSessionDto,
  ) {
    return this.plans.rescheduleSession(
      user.userId,
      dto.sessionId,
      dto.toWeekday,
    );
  }

  @Post('session/shorter')
  @HttpCode(200)
  shorter(@CurrentUser() user: AuthUser, @Body() dto: SessionActionDto) {
    return this.plans.shorterSession(user.userId, dto.sessionId);
  }

  @Post('rebalance-week')
  @HttpCode(200)
  rebalance(@CurrentUser() user: AuthUser) {
    return this.plans.rebalanceWeek(user.userId);
  }
}
